### PR TITLE
📝 Add AUR installation instructions

### PR DESCRIPTION
**Pull request by lovetocode999**

### CODE REVIEW

**Comment by makeworld-the-better-one** [comment]
Hey, thanks for making a `-git` package! I was meaning to. But could you put this under the "From Source" section in the README? Because installing from git has different guarantees then from a release.

**Comment by lovetocode999** [comment]
> Hey, thanks for making a `-git` package! I was meaning to.
You are welcome!

> But could you put this under the "From Source" section in the README? Because installing from git has different guarantees then from a release.
Will do!

-- 
lovetocode999

**Comment by makeworld-the-better-one** [comment]
Thank you!

**Comment by lovetocode999** [comment]
> Thank you!
You're welcome!

-- 
lovetocode999

**Pull request merged**
