### PR TITLE
Added Gruvbox Dark theme

### PR DESCRIPTION
**Pull request by thumbfighter**
A really colorful and updated version of Gruvbox Dark theme

### CODE REVIEW

**Comment by makeworld-the-better-one** [comment]
Thanks! Please remove all the comments at the top of the file, and add screenshots to the README. See #221 as an example.

**Comment by makeworld-the-better-one** [comment]
Looks good to me! Just confirm you're good to merge and I will.

**Comment by thumbfighter** [comment]
YES! YES PLEASE!

**Comment by makeworld-the-better-one** [comment]
Thanks! Merged.

**Comment by thumbfighter** [comment]
thank you! ☺️

**Comment by makeworld-the-better-one** [comment]
I forgot to mention this before, but please subscribe to #149 so you can stay aware of themeing updates.

**Pull request merged**
