### PR TITLE
Add a new logo and images that can be used for desktop icons

### PR DESCRIPTION
**Pull request by xyproto**
Hi,

When packaging the Arch Linux package for Amfora, I could not find any icons for the desktop shortcut. I also noticed that the current logo is an image modified from: "amphora by Alvaro Cabrera from the Noun Project", which may have an unclear license?

This pull request adds a new logo and desktop shortcut icons in several different sizes. They are rendered with Blender + Cycles and edited in Gimp. The `.blend` file is also included.

I hereby license them under the same license as this project (GPL3). 

If you don't like them and reject this pull request, that's fully understandable, since logos are very subjective, but at least you have desktop icons with a valid license available. :slightly_smiling_face: 

Best regards,
Alexander F. Rødseth

### CODE REVIEW

**Comment by makeworld-the-better-one** [comment]
Wow this is quite fancy, thank you. Having played with blender myself, I appreciate work this must have taken.

However, part of the reasoning behind the name Amfora was that two Greek amphorae were one of the symbols used to represent the [Gemini twins](https://en.wikipedia.org/wiki/Castor_and_Pollux). This relates to the project because it is a browser for the Gemini protocol.

This is why I put two amphorae on the README, because it represents the two twins. If you want to, you could try and redesign with that idea in mind, but I won't fault you if you don't, since I can't promise I'll like it ahead of time.

> I also noticed that the current logo is an image modified from: "amphora by Alvaro Cabrera from the Noun Project", which may have an unclear license?

The source image is under [CC BY 3.0](https://creativecommons.org/licenses/by/3.0/). The license is pretty clear, I'm not sure how it plays out in terms of Arch packaging. Is there some way the attribution can be made? Maybe it's listed if you run `amfora -v`?

Also, I've noticed the current image in the packages is this one from The Noun Project.



I think it'd be better if we figure out attribution and then you use the one from the README, at least for now.

---

If you do recreate this PR, two things:

Personally I'd be happy to have the .blend file, but I don't want it in the Git repo due to it's size.

And I noticed that not all the image files have the same margins proportionally. I think it'd be better if all sizes just had no margins.

**Comment by xyproto** [comment]
Ah, the explanation with the Gemini twins makes sense. :+1:

I didn't mean that the CC BY 3.0 license is unclear, though. I could not spot in the `README.md` which license the logo was licensed under (and I'm not familiar with the Noun Project). Just mentioning which license is selected in a `LICENSE` file or in the `README.md` should be more than enough, for the purposes of packaging it for Arch Linux.

I created a new render with just 2 amphora. I can update the images in the pull request with this version, if you like it.

Cheers :slightly_smiling_face: 

amfora2_128x128

**Comment by makeworld-the-better-one** [comment]
Sorry, I'm afraid the 3D look is a bit much for me. I appreciate you designing this though, thank you.

Could you update the Arch pkg with the README logo? Thanks.

**Comment by xyproto** [comment]
The README logo has a resolution of 956x637 pixels, though, which is a very unusual format for a desktop icon. It is very likely to make the menus in for instance Xfce4 look weird.

**Comment by makeworld-the-better-one** [comment]
Oh hmm. You could add extra whitespace (or empty space) to make it square then? At some point I kinda want to throw up my hands, because how much does a TUI program need a logo anyway. I'd rather have no logo then the current incorrect one.

**Comment by xyproto** [comment]
I agree. The only reason I'm asking about an icon is because Amfora includes a `.desktop` file (which usually comes with an icon and an `Icon=...` field).

**Comment by makeworld-the-better-one** [comment]
Yeah. Well I'm fine with either no icon, or a modification of the README icon so it's square. Up to you.

**Pull request closed without merging**
