### PR TITLE
Strip ANSI codes from page based on config - fixes #79

### LINKED ISSUE #79: Strip ANSI codes from page
This should happen when:
- [ ] `color = false`
- [ ] `ansi = false` - New setting, doesn't exist yet

This can be done with a small regex, see [here](https://superuser.com/questions/380772/removing-ansi-color-codes-from-text-stream).

### PR DESCRIPTION
**Pull request by sumpygump**
Adds new boolean config option `ansi` in `[a-general]` to switch whether ANSI codes in page content will be rendered to terminal.

If `ansi `is set to false or `color` is set to false, any ANSI codes will be stripped from fetched content.
Fixes #79 

Here is a summary of results for the various values of the two options:

| config: color | config: ansi | Result                                    |
|---------------|--------------|-------------------------------------------|
| true          | true         | colorize headings & links; translate ANSI |
| true          | false        | colorize headings & links; strip ANSI     |
| false         | true         | no color; strip ANSI                      |
| false         | false        | no color; strip ANSI                      |

Notice how it is not possible to have `ansi` color codes true and `color` false at the same time. If the `color` config option is false, it overrides the value of `ansi`.

Feature to only allow ansi codes in preformatted blocks is part of another issue (#59)

### CODE REVIEW

**Review by makeworld-the-better-one — CHANGES_REQUESTED** [review]
Thanks, this is helpful! I have a few issues.

- What is the source for that regex? You should put it as a comment in the code
- Define the regex as a package/global variable like `ansiRegex` or `ansiRE`
- Optionally strip ANSI in the `RenderANSI` function as well
- Add the default value of `a-general.ansi` to `config/config.go`, like all config options

You can add `//nolint:lll` right before the regex variable to make linting pass, I don't mind in this case.

**Comment by sumpygump** [comment]
Thanks for the tips. I made your suggested changes.

**Comment by makeworld-the-better-one** [comment]
The `ansiRegex` variable should be the output of `regexp.MustCompile`, not a string. Also I'd appreciate if you pointed to the source directly:
```go
// Source: https://github.com/acarl005/stripansi/blob/2749a054d4758fb0126d83aae590d7c9e8982d77/stripansi.go
```

On another level, I wonder if there's any point in stripping non-color codes only sometimes. The way things are done currently, those codes will be displayed on the screen when ANSI is enabled, but stripped when it's disabled. It might make sense to only strip color codes, since the move and other codes don't actually affect the terminal display anyway, thanks to cview.

A regex like ``` `\x1b\[[0-9;]*m` ``` (note it's a backtick string) should be able to just get the color codes. That's taken from [here](https://superuser.com/questions/380772/removing-ansi-color-codes-from-text-stream), which I linked in #79. I'm not sure why the stripansi regex is so long compared to these other ones. I've seen this longer version in other places like [here](https://github.com/chalk/ansi-regex/blob/master/index.js), but there seems to be no complaints about the shorter ones on superuser.com.

**Comment by sumpygump** [comment]
Okay, that makes sense. I was thinking that the goal would be to strip all ansi codes, worrying that things like clear screen and move would potentially mess up the rendering of the page. I'll switch it to the simpler regex.

**Pull request merged**
