### PR TITLE
cview update

### LINKED ISSUE #26: Left margin performance
In #13 I made this fix for left margins:
> just shifting the content over every time it's displayed. This is less performant, but I don't know if it would make much of a difference.

It did end up making a difference, on long documents like `gemini://tilde.black/users/fox/irc/log.txt`. It takes a long time to load, which is one thing, but also even once it's cached, it takes *20* seconds to view it after navigating away from it and coming back. This is because the left margin spaces are being added to the entire document again. One solution would be to have a `Page.LeftMargin` integer attribute. And that's only recalculated when a reload happens, which would set it back to `-1` or something.

### LINKED ISSUE #43: strange paste behaviour for address bar on Windows
I'm seeing a strange behaviour - when I try to paste a URL from the clipboard into Amfora on Windows (win10 x64) it seems to truncate the URL. Similar behaviour using the right mouse click or Edit->paste menu, both of which normally paste OK in other apps.

For example here I pasted the following URL: gemini://gemini.marmaladefoo.com/blog/7-Jul-2020_GemiNaut_v0_8_6_release.gmi

the truncation happens as you paste, before you hit enter to navigate to that URL. Amfora cannot navigate as the URL is broken.

amfora_paste_bug

### LINKED ISSUE #89: Show indicator of scroll level
Hello @makeworld-the-better-one 

I found myself reading a very long gemini post recently (for reference: gemini://l-3.space/split-keys.gmi ) and it came up in my mind that it would be nice to now how long until I reach the end.

As a possible idea, splitting the bottom status bar in two, where on the left there is the bar as there is now, and aligned on the right there is somenthing like `number_bottom_line:number_of_lines_in_document` or some form of percentage.

Ideally some form of scroll bar (vertical) or reading progress bar (horizontal).

### LINKED ISSUE #105: Theme support for help page
Could you please add keys to set the background and foreground colors for the help page? The one that's brought up by pressing `?`.

### LINKED ISSUE #161: Shift + Tab doesn't cycle through links in st terminal
## Description of the issue
I tried the amfora on master (e42b24c6f2ab8adf351ef3c6decde36f970dcd5c as of this writing) and `Shift + Tab` doesn't seem to work at all.
 `Tab` correctly cycles through the links but `Shift + Tab` expected to cycle backwards doesn't work, _nothing happens when I press both keys_.

## Environement
OS: `Linux - NixOS 21.03.20201209.e9158ec (Okapi)`
Terminal emulator: `st`

### PR DESCRIPTION
**Pull request by makeworld-the-better-one**
Fixes #43 ~~(Would appreciate if @LukeEmmet could test this)~~
Fixes #105 
Fixes #161 

## Todo
- [x] Merge `master` back into this branch and get it to compile
- [x] Replace `browser.SetCurrentTab` with `panels.HidePanel(modal)`
- [x] Make sure `panels.SendToFront` is used everywhere after `panels.ShowPanel`
- [x] Make `"help"` a panel instead of a tab
- [x] Re-implement favicons using `SetTabLabel`
- [x] Set up tab colors from config
- [x] Fix tab number and favicons when moving through history
- [x] Add `.Truecolor()` to user loaded colors and test
	- Should it be used for all colors? See [here](https://github.com/gdamore/tcell/issues/403#issuecomment-719097652) for explanation **Yes**
- [x] Fix ANSI on white terminal issue as described in [cview issue 25](https://gitlab.com/tslocum/cview/-/issues/25)
- [x] Fix background for tab dividers
- [x] Test theme changes, especially general ones like for all modal buttons and text
- [x] Fix ANSI document left margin color leaking
- [x] Replace left margin spaces with an empty primitive - fixes #26
- [ ] Replace usage of `cview.WordWrap` with using `TextView.SetWrapWidth`, see [this comment](https://gitlab.com/tslocum/cview/-/issues/27#note_441098534) - #156
	- This can't happen, see [this comment](https://gitlab.com/tslocum/cview/-/issues/27#note_475438483)
- [x] Add empty line underneath tab row
- [x] Make sure page scrollbar is enabled everywhere, make config option to turn it off, make it themeable - fixes #89

- [x] Test stuff like this still works: (Also used by `bkmkModal`):
```go
// Remove elements and re-add them - to clear input text and keep input in focus
inputModal.ClearButtons()
inputModal.GetForm().Clear(false)
```
- [x] Update to latest commit and stop using fork, test - delete fork if it works
- [ ] Extensive general testing (in progress)
- [ ] Go through TODOs

## New bugs (mark complete when fixed)
- [x] Colors are different (at least TOFU error modal)
- [x] Modal stays on screen after clicking yes (at least TOFU error modal)
- [x] `Help` appears up top as the first tab

## Upstream issues
Added to NOTES.md already

- [x] [Problems with tab row colors](https://gitlab.com/tslocum/cview/-/issues/46)
- [ ] [cview.Styles not being used](https://gitlab.com/tslocum/cview/-/issues/47) - issue is circumvented in Amfora
- [ ] [ANSI conversion is messed up](https://gitlab.com/tslocum/cview/-/issues/48)
- [ ] [WordWrap is broken in some cases](https://gitlab.com/tslocum/cview/-/issues/27#note_475438483) - clos-e #156 if this is fixed
- [x] [Remove tab row flash when reformatting](https://gitlab.com/tslocum/cview/-/issues/49)
- [ ] [Prevent panic when reformatting](https://gitlab.com/tslocum/cview/-/issues/50) - can't reliably reproduce or debug

### CODE REVIEW

**Comment by LukeEmmet** [comment]
Hi @makeworld-the-better-one. I'm happy to test these changes - let me know once it is merged and I'll try it out

**Comment by makeworld-the-better-one** [comment]
@LukeEmmet Thanks! There's currently many bugs going on, so maybe I'll @ you again right *before* merge and you can test out the issue in #43. You're also welcome to test on your own time, there just might be other bugs. Let me know and I can upload a binary. Here's a current one, no guarantees. (Windows 64-bit)

[amfora.exe.zip](https://github.com/makeworld-the-better-one/amfora/files/5461448/amfora.exe.zip)

**Comment by LukeEmmet** [comment]
hi @makeworld-the-better-one I just tried that binary - it works! Well I only tested the pasting long URL into the address box though. I'm happy to try future updates, let me know. I'm not sure if I'm confident enough to create a build based on an unmerged PR, so you might have to create a binary for me again though

**Comment by makeworld-the-better-one** [comment]
That's good enough for me! Very happy to hear that works. I might @ you later for future updates, but I don't see this regressing (since it's not my code) so I think we're good. Thanks!

**Comment by makeworld-the-better-one** [comment]
I'm not sure if anyone is watching this thread, but if they are, I'd appreciate if they could try out this PR and just do some general testing, find out if anything is broken or buggy or doesn't work like the master branch does. Thanks!

**Comment by makeworld-the-better-one** [comment]
@objectliteral @sudobash1 @ThomasAdam If any of you are interested in trying out this branch and seeing if anything is broken that would be much appreciated. It's pretty much ready at this point, the step I'm on now is just "Extensive general testing". So just try out all the features you know, use it normally, do weird things, etc. If the bug you find still happens on the master branch, you can make an issue, but otherwise just report it in this thread.

Thank you!

**Comment by ThomasAdam** [comment]
Hey @makeworld-the-better-one 

Sure!  So far, so good.  I take it that the tab bar along the top is now supposed to wrap if the number of tabs is greater than the terminal width?   The version on `master` doesn't wrap the tab bar past the terminal width.

**Comment by makeworld-the-better-one** [comment]
@ThomasAdam Interesting, I didn't expect that. The bar is done differently now. I'll see what I can do, as I think wrapping is worse off.

**Comment by objectliteral** [comment]
I noticed a difference in horizontal scrolling with the new version: When a line is long enough (or the terminal narrow enough) such that the document can be scrolled horizontally, the version in `master` scrolls into the left padding, whereas the `cview-update` version preserves the padding and cuts off the text.

Can be easily reproduced with preformatted text:

`echo -e "```\nA really long line of text that is preformatted to it won't wrap and will cause you to be able to do horizontal scrolling... Maybe need some Lorem Ipsum in here, but I'm too lazy to generate some. Oh and I hope you don't test on a ultra-wide monitor...\n```\nHere is normal text" > wrap.gmi`

I don't know which of the two scrolling behaviors is prefered. (I think I like the old one better...)

**Comment by makeworld-the-better-one** [comment]
@objectliteral Thanks for reminding me about this. See 90654cd and #26 for why this happened. Basically the old left margin was just spaces that was stored as part of the page rendering. Now it's done as a flex element, which is much much more efficient.

However I think this is out of scope for this PR. I can make a new issue for this when this gets merged.

**Comment by makeworld-the-better-one** [comment]
@ThomasAdam I filed [this issue](https://gitlab.com/tslocum/cview/-/issues/54) with cview about the tab bar wrapping. It will not be fixed before this PR is merged.

**Pull request merged**
