### PR TITLE
add slimey.toml

### PR DESCRIPTION
**Pull request by lee2sman**

### CODE REVIEW

**Comment by makeworld-the-better-one** [comment]
Thanks! Please also add screenshots of the theme, see [`contrib/themes/README.md`](https://github.com/makeworld-the-better-one/amfora/blob/master/contrib/themes/README.md) or #221 as an example.

**Comment by lee2sman** [comment]
where does the image file go?

**Comment by makeworld-the-better-one** [comment]
Most people have been hosting it through GitHub, but not in this repo. For example, if you were to upload your screenshot as a comment on this PR, and then use that link.

**Comment by lee2sman** [comment]
slimey-amfora-theme

**Comment by lee2sman** [comment]
Okay, hopefully I did that correctly! Thanks for your patience.

**Comment by makeworld-the-better-one** [comment]
One more thing, add a "Contributed by" line if you like, as the other themes have. Sorry I didn't mention this before!

**Comment by lee2sman** [comment]
Added!

**Comment by makeworld-the-better-one** [comment]
Thanks!

**Comment by makeworld-the-better-one** [comment]
Small fix to the README I missed in d2004d9

**Comment by makeworld-the-better-one** [comment]
@lee2sman please subscribe to #149 so you can stay aware of themeing updates.

**Pull request merged**
