### PR TITLE
show links

### PR DESCRIPTION
**Pull request by p1gp1g**

### CODE REVIEW

**Comment by makeworld-the-better-one** [comment]
I'm not sure what this PR adds. It seems like link lines would become quite long like this. Personally if want to view the URL, I use the Tab and Shift-Tab keys. You can use Esc to stop selecting. What do you think?

**Comment by p1gp1g** [comment]
Actually, I really don't like to clic on a link I haven't seen. The miss of this is even blocking for me. And I prefer to navigate with \<space\>+N°. For the moment I haven't seen a link written on 2 lines. 

I knew it would not be the choice of every body, that's why I set the default to false.

**Comment by makeworld-the-better-one** [comment]
Alright. Please add the config changes to `default-config.toml` as well, and change the line that reads `linkText = linkText + " (" + url + ")"` to `linkText += " (" + url + ")"` instead. Thanks!

**Comment by makeworld-the-better-one** [comment]
Thanks, merged.

**Comment by p1gp1g** [comment]
Thanks :)

**Pull request merged**
