### PR TITLE
deps: update to use go1.17

### PR DESCRIPTION
**Pull request by chenrui333**
update golang.org/x/sys to the latest

cc @makeworld-the-better-one

### CODE REVIEW

**Comment by makeworld-the-better-one** [comment]
What's the point of this PR? Amfora intends to support Go 1.15+ anyway. Also note that this is failing to build on Go 1.17.

**Comment by chenrui333** [comment]
> What's the point of this PR? Amfora intends to support Go 1.15+ anyway. Also note that this is failing to build on Go 1.17.

Using the latest version of go would help identify the compatibility issue (go 1.16+ has made go modules build as default, and as you can see go1.17 has different layout for `go.mod`).

**Comment by chenrui333** [comment]
I thought I already updated the `go.sum`, let me check on it again.

The `golangci-lint` seems not related to my PR?

**Comment by makeworld-the-better-one** [comment]
> Using the latest version of go would help identify the compatibility issue

What compatibility issue? Amfora has been working fine for all Go versions it's supposed to support.

**Comment by chenrui333** [comment]
> > Using the latest version of go would help identify the compatibility issue
> 
> What compatibility issue? Amfora has been working fine for all Go versions it's supposed to support.

Yeah, it does as of now. 

Let me ask the other way around, what is the challenge of accepting this PR?

**Comment by makeworld-the-better-one** [comment]
> Let me ask the other way around, what is the challenge of accepting this PR?

It doesn't work that way. The author has to prove the value of the PR before it can be accepted. I don't see the point of changing the versions and all these dependencies around. I think it could hurt compatibility for Go versions <1.17 to put `go 1.17` in `go.mod`.

But this is all besides the point because it doesn't even build on Go 1.17:

image

**Comment by chenrui333** [comment]
make sense, we can revisit this along with the go1.18 and later.

**Comment by makeworld-the-better-one** [comment]
You're welcome to submit another PR at some point, but it has to provide a clear advantage over the existing code. Right now I'm happy with the way my module setup is.

**Comment by chenrui333** [comment]
yeah, totally. thanks for the input though! :)

**Pull request closed without merging**
